package dev.d1s.initializr.api

import dev.d1s.initializr.util.fromRawString

public enum class ProjectDependency(
    public val projectName: String,
    public override val raw: String
) : RawView {
    THYMELEAF("Thymeleaf", "thymeleaf"),
    SPRING_NATIVE("Spring Native", "native"),
    SPRING_BOOT_DEVTOOLS("Spring Boot DevTools", "devtools"),
    LOMBOK("Lombok", "lombok"),
    SPRING_CONFIGURATION_PROCESSOR("Spring Configuration Processor", "configuration-processor"),
    SPRING_WEB("Spring Web", "web"),
    SPRING_REACTIVE_WEB("Spring Reactive Web", "webflux"),
    REST_REPOSITORIES("Rest Repositories", "data-rest"),
    SPRING_SESSION("Spring Session", "session"),
    REST_REPOSITORIES_HAL_EXPLORER("Rest Repositories HAL Explorer", "data-rest-explorer"),
    SPRING_HATEOAS("Spring HATEOAS", "hateoas"),
    SPRING_WEB_SERVICES("Spring Web Services", "web-services"),
    JERSEY("Jersey", "jersey"),
    VAADIN("Vaadin", "vaadin"),
    APACHE_FREEMARKER("Apache Freemarker", "freemarker"),
    MUSTACHE("Mustache", "mustache"),
    GROOVY_TEMPLATES("Groovy Templates", "groovy-templates"),
    SPRING_SECURITY("Spring Security", "security"),
    OAUTH2_CLIENT("OAuth2 Client", "oauth2-client"),
    OAUTH2_RESOURCE_SERVER("OAuth2 Resource Server", "oauth2-resource-server"),
    SPRING_LDAP("Spring LDAP", "data-ldpa"),
    OKTA("Okta", "okta"),
    JDBC_API("JDBC API", "jdbc"),
    SPRING_DATA_JPA("Spring Data JPA", "data-jpa"),
    SPRING_DATA_JDBC("Spring Data JDBC", "data-jdbc"),
    SPRING_DATA_R2DBC("Spring Data R2DBC", "data-r2dbc"),
    MYBATIS_FRAMEWORK("MyBatis Framework", "mybatis"),
    LIQUIBASE_MIGRATION("Liquibase Migration", "liquibase"),
    FLYWAY_MIGRATION("Flyway Migration", "flyway"),
    JOOQ_ACCESS_LAYER("JOOQ Access Layer", "jooq"),
    IBM_DB2_DRIVER("IBM DB2 Driver", "db2"),
    APACHE_DERBY_DATABASE("Apache Derby Database", "derby"),
    H2_DATABASE("H2 Database", "h2"),
    HYPERSQL_DATABASE("HyperSQL Database", "hsql"),
    MARIADB_DRIVER("MariaDB Driver", "mariadb"),
    MS_SQL_SERVER_DRIVER("MS SQL Server Driver", "sqlserver"),
    MYSQL_DRIVER("MySQL Driver", "mysql"),
    ORACLE_DRIVER("Oracle Driver", "oracle"),
    POSTGRESQL_DRIVER("PostgreSQL Driver", "postgresql"),
    SPRING_DATA_REDIS("Spring Data Redis", "data-redis"),
    SPRING_DATA_REACTIVE_REDIS("Spring Data Reactive Redis", "data-redis-reactive"),
    SPRING_DATA_MONGODB("Spring Data MongoDB", "data-mongodb"),
    SPRING_DATA_REACTIVE_MONGODB("Spring Data Reactive MongoDB", "data-mongodb-reactive"),
    SPRING_DATA_ELASTICSEARCH("Spring Data Elasticsearch", "data-elasticsearch"),
    SPRING_DATA_FOR_APACHE_CASSANDRA("Spring Data for Apache Cassandra", "data-cassandra"),
    SPRING_DATA_REACTIVE_FOR_APACHE_CASSANDRA("Spring Data Reactive for Apache Cassandra", "data-cassandra-reactive"),
    SPRING_FOR_APACHE_GEODE("Spring Data for Apache Geode", "geode"),
    SPRING_DATA_COUCHBASE("Spring Data Couchbase", "data-couchbase"),
    SPRING_DATA_REACTIVE_COUCHBASE("Spring Data Reactive Couchbase", "data-couchbase-reactive"),
    SPRING_DATA_NEO4J("Spring Data Neo4j", "data-neo4j"),
    SPRING_INTEGRATION("Spring Integration", "integration"),
    SPRING_FOR_RABBITMQ("Spring for RabbitMQ", "amqp"),
    SPRING_FOR_APACHE_KAFKA("Spring for Apache Kafka", "kafka"),
    SPRING_FOR_APACHE_KAFKA_STREAMS("Spring for Apache Kafka Streams", "kafka-streams"),
    SPRING_FOR_APACHE_ACTIVEMQ_5("Spring for Apache ActiveMQ 5", "activemq"),
    SPRING_FOR_APACHE_ACTIVEMQ_ARTEMIS("Spring for Apache ActiveMQ Artemis", "artemis"),
    WEBSOCKET("WebSocket", "websocket"),
    RSOCKET("RSocket", "rsocket"),
    APACHE_CAMEL("Apache Camel", "camel"),
    SPRING_BATCH("Spring Batch", "batch"),
    VALIDATION("Validation", "validation"),
    JAVA_MAIL_SENDER("Java Mail Sender", "mail"),
    QUARTZ_SCHEDULER("Quartz Scheduler", "quartz"),
    SPRING_CACHE_ABSTRACTION("Spring cache abstraction", "cache"),
    SPRING_BOOT_ACTUATOR("Spring Boot Actuator", "actuator"),
    CODECENTRIC_SPRING_BOOT_ADMIN_CLIENT(
        "Codecentric's Spring Boot Admin Client",
        "codecentric-spring-boot-admin-client"
    ),
    CODECENTRIC_SPRING_BOOT_ADMIN_SERVER(
        "Codecentric's Spring Boot Admin Server",
        "codecentric-spring-boot-admin-server"
    ),
    INFLUX("Influx", "influx"),
    DATADOG("Datadog", "datadog"),
    GRAPHITE("Graphite", "graphite"),
    NEW_RELIC("New Relic", "new-relic"),
    PROMETHEUS("Prometheus", "prometheus"),
    SLEUTH("Sleuth", "cloud-starter-sleuth"),
    WAVEFRONT("Wavefront", "wavefront"),
    ZIPKIN_CLIENT("Zipkin Client", "cloud-starter-zipkin"),
    SPRING_REST_DOCS("Spring REST Docs", "restdocs"),
    TESTCONTAINERS("Testcontainers", "testcontainers"),
    CONTRACT_VERIFIER("Contract Verifier", "cloud-contract-verifier"),
    CONTRACT_STUB_RUNNER("Contract Stub Runner", "cloud-contract-stub-runner"),
    EMBEDDED_LDAP_SERVER("Embedded LDAP Server", "unboundid-ldap"),
    EMBEDDED_MONGODB_DATABASE("Embedded MongoDB Database", "flapdoodle-mongo"),
    CLOUD_BOOTSTRAP("Cloud Bootstrap", "cloud-starter"),
    FUNCTION("Function", "cloud-function"),
    TASK("Task", "cloud-task"),
    CONFIG_CLIENT("Config Client", "cloud-config-client"),
    CONFIG_SERVER("Config Server", "cloud-config-server"),
    VAULT_CONFIGURATION("Vault Configuration", "cloud-starter-vault-config"),
    APACHE_ZOOKEEPER_CONFIGURATION("Apache Zookeeper Configuration", "cloud-starter-zookeeper-config"),
    CONSUL_CONFIGURATION("Consul Configuration", "cloud-starter-consul-config"),
    EUREKA_DISCOVERY_CLIENT("Eureka Discovery Client", "cloud-eureka"),
    EUREKA_SERVER("Eureka Server", "cloud-eureka-server"),
    APACHE_ZOOKEEPER_DISCOVERY("Apache Zookeeper Discovery", "cloud-starter-zookeeper-discovery"),
    CLOUD_FOUNDRY_DISCOVERY("Cloud Foundry Discovery", "cloud-cloudfoundry-discovery"),
    CONSUL_DISCOVERY("Consul Discovery", "cloud-starter-consul-discovery"),
    GATEWAY("Gateway", "cloud-gateway"),
    OPENFEIGN("OpenFeign", "cloud-feign"),
    CLOUD_LOADBALANCER("Cloud LoadBalancer", "cloud-loadbalancer"),
    RESILIENCE4J("Resilience4j", "cloud-resilience4j"),
    CLOUD_BUS("Cloud Bus", "cloud-bus"),
    CLOUD_STREAM("Cloud Stream", "cloud-stream"),
    AZURE_SUPPORT("Azure Support", "azure-support"),
    AZURE_ACTIVE_DIRECTORY("Azure Active Directory", "azure-active-directory"),
    AZURE_COSMOS_DB("Azure Cosmos DB", "azure-cosmos-db"),
    AZURE_KEY_VAULT("Azure Key Vault", "azure-keyvault-secrets"),
    AZURE_STORAGE("Azure Storage", "azure-storage"),
    GCP_SUPPORT("GCP Support", "cloud-gcp"),
    GCP_MESSAGING("GCP Messaging", "cloud-gcp-pubsub"),
    GCP_STORAGE("GCP Storage", "cloud-gcp-storage"),
    SPRING_GRAPHQL("Spring GraphQL", "graphql"),
    SOLACE_PUBSUB_PLUS("Solace PubSub+", "solace"),
    PICOCLI("Picocli", "picocli"),
    OPEN_SERVICE_BROKER("Open Service Broker", "open-service-broker"),
    CONFIG_CLIENT_TAS("Config Client (TAS)", "scs-config-client"),
    SERVICE_REGISTRY_TAS("Service Registry (TAS)", "scs-service-registry");

    public companion object {
        public fun fromRaw(raw: String): ProjectDependency = fromRawString(raw)
    }
}